### ISSUE TITLE
Repeated message "No root module found for <filename> functionality may be limited"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [hashicorp/terraform-ls#221] opened 2020-07-06 07:44 UTC
With version 2.0.2 of the hashicorp.terraform extension, whenever I open a file, I'm getting this message.

Directory structure of the environment looks like this:

```
PROJECT_DIR
+--Terraform
|  +--Infra
|  |   +--main.tf
|  |   +--vars.tf
|  |   \--output.tf
|  +--Vendor
|      +--main.tf
|      +--vars.tf
|      \--output.tf
+--Ansible
   +--main.yml
```

Happy to provide any support to identify why this is occurring. It's not a major issue for me right now, but it might be useful to provide some kind of inline remediation technique to resolve this message?

**Comment by radeksimko** [comment] 2020-07-09 21:23
@divmgl Re high CPU - Do you mind following the same troubleshooting steps and help provide some more data as discussed in https://github.com/hashicorp/terraform-ls/issues/217 ? I would like to look into that and get to a point where I can reproduce it. Thanks.

This seems unrelated to what is being discussed here, so let's take that to #217

**Comment by radeksimko** [comment] 2020-07-09 21:34
@navisidhu That is a good observation. Generally the server doesn't yet have the capability to detect`terraform init` "from scratch", but it's certainly something that I'd like to address - see https://github.com/hashicorp/terraform-ls/issues/222

**Comment by radeksimko** [comment] 2020-07-09 21:43
I plan to release 1.4.2 in coming day(s) which improves the messaging and makes various loading operations asynchronous which may have some positive implications for the troubleshooting here. I will comment here when the release is out.

I will also have a think about setting up a dedicated section for troubleshooting this particular error message, which we can guide people to, and perhaps even link it from the warning message.

**Comment by radeksimko** [comment] 2020-07-10 18:30
I have just published `0.5.0`. This update should pop up automatically on the next VSCode launch, unless you configured it to point to a custom build. This should at least communicate that `terraform init` may be needed.

There is still some work left to do though around logging of certain failures as per https://github.com/hashicorp/terraform-ls/issues/218 - that will help us better understand what's going on and why root modules were not found, even though communicating it through the log still may not always be the most practical debugging approach.

Complex hierarchies can overall be addressed in a few ways:
 - configurable root modules should allow you to supply a list of paths as a "hint" when the discovery fails - https://github.com/hashicorp/terraform-ls/pull/198 was already shipped as part of 0.5.0, but there's more work needed on the VSCode extension side to support this tracked under https://github.com/hashicorp/vscode-terraform/pull/423
 - provide some way of invoking the discovery and collecting all the discovered data about a folder and its hierarchy as per https://github.com/hashicorp/terraform-ls/issues/225
 - understand what are the hierarchies which don't get discovered automatically at all and why (which would be difficult without the above)
 - build better support for certain known complex hierarchies as per https://github.com/hashicorp/terraform-ls/issues/179 and https://github.com/hashicorp/terraform-ls/issues/180

**Comment by andriktr** [comment] 2020-07-11 11:42
Same issue here "No root module found for <filename> functionality may be limited" and autocomplete is not working :(

**Comment by yoshiotobe** [comment] 2020-07-12 03:21
I use codes just for reference. However, I get the message repeatedly when reading the codes because the codes can not be initialized. Is there any ways to disable the message? 
I don't know if this message is necessary if it just prompt you to do "terraform init" because you will know when you execute the codes.

**Comment by shivani-dunzo** [comment] 2020-07-14 11:04
Happened for me when I did relaunch VSCode. 

I am using Terraform v0.11.13. I have manually updated VSIX package: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version and removed other extensions for terraform. Works well for me now. This is just for Terraform v0.11.

**Comment by shivani-ahuja** [comment] 2020-07-14 11:07
Happened for me when I did relaunch VSCode.
I am using Terraform v0.11.13. I have manually updated VSIX package: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version and removed other extensions for terraform. Works well for me now. This is just for Terraform v0.11.

**Comment by shivaniahuja** [comment] 2020-07-14 11:13
Happened for me when I did relaunch VSCode.
I am using Terraform v0.11.13. I have manually updated VSIX package: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version and removed other extensions for terraform. Works well for me now. This is just for Terraform v0.11.

**Comment by radeksimko** [comment] 2020-07-14 14:18
@shivaniahuja This language server generally doesn't support <0.12 except for basic functionality like formatting. I guess we could surface that fact via a more relevant warning, when we 0.11 was found - as this message would be far more relevant than "No root module found".

**Comment by jhonnyx82** [comment] 2020-07-18 21:36
Hi there,

I am having this exact issue but only when I open VScode and apparently only autocompletion is not working.

versions:
VScode : 1.47.2
Terraform : v0.12.28
--- google provider v3.5.0
Terraform LS : 0.5.2
WSL version 1

Terraform extension and Terraform LS were installed via VScode itself, and I can see the terraform LS server is running on WSL.

**Comment by radeksimko** [comment] 2020-07-20 08:31
@g1augusto Unfortunately it's unlikely that we'd be able to diagnose the problem without logs. Would you mind sharing these? See https://github.com/hashicorp/terraform-ls/blob/master/docs/TROUBLESHOOTING.md#logging for more.

**Comment by g1augusto** [comment] 2020-07-20 09:19
@radeksimko 

I have added here the logs generated by the terraform language server module in VScode
[terraform-ls-1389.log](https://github.com/hashicorp/terraform-ls/files/4946677/terraform-ls-1389.log)

Let me know if you need more info or if I have to proceed differently with the logs export

**Comment by brettcurtis** [comment] 2020-07-20 23:39
We have the same problem. We are specifically developing child modules and testing them through GitHub actions. Our tree looks like this:

```none
.
├── .github
   └── workflows
       ├── terraform.yml
       └── test
           ├── backend.tf
           ├── main.tf
           ├── plan.out
           ├── tfvars
           │   └── new-cloud-sql.tfvars
           └── variables.tf
├── local.tfvars.EXAMPLE
├── main.tf
├── outputs.tf
└── variables.tf
```

We 'hide' all the testing code for the GitHub action in the .github/workflows/test directory. The main.tf there actually calls the child module like so:

```hcl
provider "google" {
}

resource "random_id" "random" {
  byte_length = "3"
}

module "cloud-sql" {
  source = "../../../"

  project_id    = var.project_id
  instance_name = "${var.instance_name}-${random_id.random.hex}"
  machine_tier  = var.machine_tier
}
```

That's the why behind our directory structure. Running init in the root module directory or child module directory doesn't seem to help. I get that warning message every time I select a .tf file. I'm using workspaces as well, just as a FYI that seems to throw off a few other plugins so I figured I'd mention it. I can share logs if helpful as well.

**Comment by radeksimko** [comment] 2020-07-21 06:33
@g1augusto It looks like you have multiple folders open in VS Code, which in turn means you are hitting this bug https://github.com/hashicorp/vscode-terraform/issues/434 The only workarounds for now would be [declaring root module paths](https://github.com/hashicorp/terraform-ls/blob/master/docs/SETTINGS.md#rootmodulepaths-string) explicitly (support for relative paths [is coming](https://github.com/hashicorp/terraform-ls/issues/235)), or opening just one folder at a time in VS Code.

**Comment by radeksimko** [comment] 2020-07-21 06:43
@brettcurtis Unfortunately I cannot tell from the details you provided what the reason may be. Logs would be helpful.

> Running init in the root module directory or child module directory doesn't seem to help.

Just FYI you may need to restart the editor when you `init` a directory which wasn't init'd previously for it to be picked up - something we plan to address as part of https://github.com/hashicorp/terraform-ls/issues/222

**Comment by brettcurtis** [comment] 2020-07-21 12:23
@radeksimko looks like I'm hitting the same issue as @g1augusto. I just tried opening this individual folder in vscode and it work. If I open it in a vscode workspace with other folders I get the warning.

**Comment by dominik-ba** [comment] 2020-07-28 10:11
Actually I'm more interested in syntax highlighting and not actually running terraform locally. Is it possible to simply turn that message off and ignoring it?

**Comment by g1augusto** [comment] 2020-07-28 10:48
About syntax highlighting, is that normal that module resources and variables are not listed while editing a root module?

Just asking if this is material for a feature request or if is related to this issue

**Comment by radeksimko** [comment] 2020-07-28 13:37
Syntax highlighting is generally not handled by the language server since the LSP itself doesn't support that yet, so I would file any such feature requests under the relevant editor extension repo (e.g. [vscode-terraform](https://github.com/hashicorp/vscode-terraform) if you use the VS Code extension, or [Terraform.tmlanguage](https://github.com/alexlouden/Terraform.tmLanguage) if you use Sublime Text etc.). Each editor/extension implements this differently.

**Comment by denis-peshkov** [comment] 2020-08-12 21:22
**still not working for me**

```
.
├── .vscode
        └── settings.json
├── environments
        ├── dev
                ├── main.tf
                ├── output.tf
                └── providers.tf
        └── prod
                ├── main.tf
                ├── output.tf
                └── providers.tf
└── modules
        └── azure
                ├── app.tf
                ├── main.tf
                ├── output.tf
                ├── plan.tf
                ├── sb.tf
                └── variables.tf
```
settings.json
```
{
  "terraform-ls.rootModules": [
    "./modules/azure",
    "./environments/dev",
    "./environments/prod"
  ]
}
```

**Comment by austinarbor** [comment] 2020-09-02 16:04
Using terraform `v0.11.14`, manually installing https://github.com/hashicorp/vscode-terraform/releases/tag/1.3.12 fixes all functionality for me

**Comment by viktors-telle** [comment] 2020-09-09 12:52
Intellisense (autocomplete) started to work with `v2.2.3 ` of [terraform](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) plugin.

**Comment by andriktr** [comment] 2020-09-09 19:18
For me started to work as well

**Comment by g1augusto** [comment] 2020-09-23 18:41
> Intellisense (autocomplete) started to work with `v2.2.3` of [terraform plugin](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) and Terraform `v0.12.24`.

Unfortunately for me not yet 
terraform plugin : 2.2.3
terraform binary : 0.13.3

syntax highlighting is there but auto-completion gives odd results, sometimes it refers to resources I have modified (but still offered in the autocomplete) and I still have the "no root module found in the directory" even if I add the actual directory in the terraform plugin settings or if I open the workspace on the specific base directory of the main.tf file (init'ed)

**Comment by santosh-aws002** [comment] 2020-10-29 06:38
In cmd/terminal hit terraform init
and then kill the vs code and open again.

**Comment by ronjouch** [comment] 2020-10-29 17:30
I'm also:

1. Unable to use autocompletion
2. Unable to use `"terraform-ls.rootModules"`
3. Unsure whether in VSCode I should pass `"terraform-ls.rootModules"` as offered by the extension, or `"terraform-ls.rootModulePaths"` as indicated by [tf-ls doc](https://github.com/hashicorp/terraform-ls/blob/master/docs/SETTINGS.md#rootmodulepaths-string)
4. Finally, trying to pass both `"terraform-ls.rootModules"` and `"terraform-ls.rootModulePaths"` with an array containing a string of the full path of my single tf project, I still get one running `terraform-ls` process per workspace item (which makes no sense, only one of those contains TF resources, the rest are all JS/TS projects 😕).
![screenshot_lots-of-terraform-ls-processes_2020-10-29-13:23:37](https://user-images.githubusercontent.com/522085/97609526-19279c00-19ea-11eb-88fc-8620a91c0089.png)

A bit more documentation & examples would be great.

**Comment by yoshiotobe** [comment] 2020-11-12 08:25
Is this any ways to disable this message? I leave some files without root module because I don't use those files right now but I might use them in the future. However, when I refer those files I get the message repeatedly. It would be nice for users to have the choice of enabling or disabling warning.

**Comment by mugx-fc** [comment] 2020-11-19 08:03
I have the same warning using the VSCode HashiCorp Terraform plugin:

<img width="542" alt="Screenshot 2020-11-19 at 07 52 30" src="https://user-images.githubusercontent.com/54804348/99637203-6b356d80-2a3c-11eb-95db-e5926fae7933.png">

no idea how to disable it 🤔

**Comment by simonbrady** [comment] 2021-01-15 02:08
If you only need syntax highlighting and can live without features like autocomplete, a brute-force way to disable the warning is to execute "Terraform: Disable language server" from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette). You can execute "Terraform: Enable language server" when you want full functionality back.

**Comment by Brice-D** [comment] 2021-02-04 07:46
do someone already resolve this issue?

**Comment by radeksimko** [comment] 2021-02-25 18:03
Hi folks,
The issue is not addressed _yet_, but we have a plan for addressing it and I'm just merging all the issues with the same root cause, such as this one, into a single issue: https://github.com/hashicorp/terraform-ls/issues/424

Thank you for your understanding and patience.

**Closed by radeksimko** 2021-02-25 18:03 UTC
