### ISSUE TITLE
RIP: My Battery

### ISSUE THREAD

**Issue by rojopolis** [hashicorp/terraform-ls#232] opened 2020-07-13 22:21 UTC
### Server Version

```
0.5.1
```

### Terraform Version

```
Terraform v0.12.24
```

### Client Version

```
VSCode 1.47.0
```

### Terraform Configuration Files

```hcl

```

### Actual Behavior

Lately I have found my laptop with a dead battery in the morning despite the fact that it's plugged in to power.  To troubleshoot this I have been watching the power consumption of applications in Activity Monitor.  terraform-ls is a frequent list topper and I suspect it's responsible for the battery issue since it began around the same time I updated the VSCode plugin.
![Screen Shot 2020-07-13 at 3 12 24 PM](https://user-images.githubusercontent.com/39421615/87359374-7f141480-c51c-11ea-9cfa-a83c569db2ca.png)

**Comment by radeksimko** [comment] 2020-07-14 06:18
Hi @rojopolis 
I'm guessing that energy impact may correlate with CPU and/or memory usage. With that in mind I'm going to close this as a duplicate of #217 - can you please follow the steps I described in https://github.com/hashicorp/terraform-ls/issues/217#issuecomment-657716105 - I'd like to get to the bottom of this, but we need more data.

Thanks.

**Closed by radeksimko** 2020-07-14 06:18 UTC
