### ISSUE TITLE
Server initialization failed. Message: too many open files Code: -32098

### ISSUE THREAD

**Issue by obi-juan1971** [hashicorp/terraform-ls#174] opened 2020-06-19 20:09 UTC
### Server Version

```
0.3.2
```

### Terraform Version

```
Terraform v0.12.26
```

### Client Version

```
The HashiCorp Terraform Visual Studio Code (VS Code) extension v2.0.1
```

### Terraform Configuration Files

```hcl
# Terraform configuration
terraform {
  backend "remote" {
    organization = "xxxxxxxx"

    workspaces {
      name = "XXXXXX-Autoscaling"
    }
  }
  required_providers {
    aws = "~> 2.66.0"
  }  
}

provider "aws" {
  profile = "XXXXXX-Prod"
  region  = "us-east-1"
}

# Instance XXXXXX
data "aws_instance" "xxxxxx" {
  filter {
    name   = "tag:Name"
    values = [var.ec2_xxxxxx_name]
  }
}

resource "aws_ami_from_instance" "xxxxxx" {
  name                    = "prod-xxxxxx-autoscaling-test02"
  source_instance_id      = data.aws_instance.xxxxxx.id
  snapshot_without_reboot = true
}
```

### Expected Behavior

Server start and code completion full functional

### Actual Behavior

Server doesn't start and code completion doesn't work

**Comment by radeksimko** [comment] 2020-06-20 08:28
Hi @obi-juan1971 
Will you please provide the log as per the [troubleshooting instructions](https://github.com/hashicorp/terraform-ls/blob/master/docs/TROUBLESHOOTING.md)?

Thanks.

**Comment by obi-juan1971** [comment] 2020-06-20 12:33
> Hi @obi-juan1971
> Will you please provide the log as per the [troubleshooting instructions](https://github.com/hashicorp/terraform-ls/blob/master/docs/TROUBLESHOOTING.md)?
> 
> Thanks.

Hi @radeksimko 
Thanks for your responce.
I realice that the problem was on my system (Opensuse Leap 15.1) due to other applications I had opened at the same time.

The solution was to increise the open files limit according to this post:
https://easyengine.io/tutorials/linux/increase-open-files-limit/

**Comment by radeksimko** [comment] 2020-06-22 08:25
Understood.

If the error was caused by either client or server opening too many files themselves, then that's certainly something to address, but that doesn't seem to be the case here.
You may suggest that we detect free file limit before attempting to open a new file/process, but that approach would likely be very error prone, because:

 - files are being opened and closed all the time
 - we may not have sufficient access to check the limit
 - doing this cross-platform (Linux, macOS, Windows, BSD) is not trivial

With that in mind I'm going to close this, but I would certainly be interested to hear if this occurs as a result of either client or server attempting to open too many files.

**Closed by radeksimko** 2020-06-22 08:25 UTC
