### ISSUE TITLE
terraform-ls 0.18.2 causing high CPU and max memory utilization

### ISSUE THREAD

**Issue by lysacor** [hashicorp/terraform-ls#574] opened 2021-07-01 22:02 UTC
### Server Version

```
0.18.2
```

### Terraform Version

```
Terraform v0.15.5
on windows_amd64
```

### Client Version

```
Visual Studio Code 1.57.1
```

### Terraform Configuration Files

```hcl

```

### Expected Behavior

Running quietly in the background

### Actual Behavior

Started with near 100 percent CPU and began consuming RAM as quickly as it could obtain it.

### Steps to Reproduce

Once the terraform-ls server updated to 0.18.2, the behavior above started occurring. I can say that the main.tf and local.tf that in the folder where I consistently see the behavior is quite long, and includes the azurerm_azure_firewall_policy_rule_collection_group resource call and azurerm_azure_ip_groups modules. This behavior does not occur on simpler terraform files. This just started happening when 0.18.2 was updated on Visual Studio Code. I cannot share parts of the terraform code due to there being proprietary data.

**Comment by KyleKotowick** [comment] 2021-07-02 00:14
Confirmed, it just crashed my comp with 64GB RAM when I tried to save 3 open files. This is a critical bug.

**Comment by KyleKotowick** [comment] 2021-07-02 00:15
This is a duplicate of #573

**Closed** 2021-07-02 00:39 UTC
