### ISSUE TITLE
Errors when creating a new resource block from Emacs lsp-mode

### ISSUE THREAD

**Issue by amasover** [hashicorp/terraform-ls#100] opened 2020-05-13 23:38 UTC
### Server Version

```
0.2.0
```

### Terraform Version

```
0.12.24
```

### Client Version

```
Emacs with latest lsp-mode
```

### Terraform Configuration Files

Tested on a simplified example [from here](https://github.com/gruntwork-io/intro-to-terraform/blob/master/database/main.tf)
```hcl
terraform {
  required_version = ">= 0.12"
}
provider "aws" {
  region = "us-east-2"
}
resource "aws_db_instance" "example" {
  identifier_prefix   = "terraform-up-and-running"
  engine              = "mysql"
  allocated_storage   = 10
  instance_class      = "db.t2.micro"
  name                = "example_database"
  username            = "admin"
  password            = var.test
}
```
I see this behavior in any tf file though.

### Log Output

https://gist.github.com/amasover/edfcae415ac4b67a461a09e234721be3

### Expected Behavior

Autocomplete when creating a new resource block.

### Actual Behavior

Errors like so:

```
2020/05/13 17:24:22 rpc_logger.go:45: Error for "textDocument/completion" (ID 2): [-32098] invalid position: 16:2
2020/05/13 17:24:22 rpc_logger.go:45: Error for "textDocument/completion" (ID 3): [-32098] finding HCL block failed: invalid position: hcl.Pos{Line:17, Column:4, Byte:388} in main.tf:1,1-18,1
```

### Steps to Reproduce

1. Open any terraform file in Emacs, with `lsp-mode` installed.
2. Start creating a new resource.
3. There is no auto-complete for the resource block (neither on the word `resource` itself, or on the name of the resource, such as `aws_db_instance`)

**Comment by paultyng** [comment] 2020-05-14 01:01
I believe this is a duplicate of #57. This functionality isn't completed yet, but on our short list.

**Closed** 2020-05-14 01:02 UTC

**Comment by radeksimko** [comment] 2020-05-14 06:29
> There is no auto-complete for the resource block (neither on the word `resource` itself, or on the name of the resource, such as `aws_db_instance`)

Just to add to what said Paul above - I assume you were trying to trigger completion near the end of the attached snippet - i.e. outside of any block. That doesn't work yet either, but the completion of first-class keywords is tracked under https://github.com/hashicorp/terraform-ls/issues/18

The other issue #57 hopefully goes into enough detail to describe what exactly doesn't work and will work after it's implemented - in short it's triggering completion in `resource "HERE"`. Completion _will_ work there if you add the braces `{}`. i.e. turn it into `resource "" {}` - then you should get a list of resource types. Perhaps not very convenient, but it's a workaround for now.

**Comment by amasover** [comment] 2020-05-14 17:22
Yes, I was trying to trigger completion at the end of the snippet, outside any block.

I appreciate the detailed response. I didn't realize support hadn't been added yet. But at the same time, I'm really excited to see the progress on this language server. Thank you very much for your work on it :smiley:
