### ISSUE TITLE
Formatting should work regardless of workspace/initialization state

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#165] opened 2020-06-15 19:46 UTC
### Expected Behavior

Document and range formatting should work regardless of initialization state or presence of TF files in the root directory.

### Actual Behavior

Formatting does not function in those cases.

**Comment by radeksimko** [comment] 2020-06-16 08:37
This is basically a duplicate of https://github.com/hashicorp/terraform-ls/issues/83 but we can keep this one open as folks may not understand the full impact of #83 based on the description there.

**Comment by radeksimko** [comment] 2020-06-22 08:26
This was addressed by #171 and formatting will work without initialization in `0.4.0`.

**Comment by radeksimko** [comment] 2020-06-23 17:28
Just realized this actually still doesn't work yet, because we aren't adding unintialized root modules at this point and hence the executor lookup fails.

**Closed** 2020-06-24 13:46 UTC
Labels: bug, textDocument/formatting
