### ISSUE TITLE
Nested intellisense still not working

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/terraform-ls#1297] opened 2023-05-31 14:51 UTC
According to the [changelog](
https://github.com/hashicorp/terraform-ls/blob/v0.31.0/CHANGELOG.md), I think this was implemented?

> Add support for nested expressions and functions

Unfortunately it's not working for me :(

### Server Version

```
serve_command.go:104: Starting terraform-ls 0.31.2
```

### Terraform Version

```
$ tf -v       
Terraform v1.4.6
on windows_386
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.58.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/microsoft/azuredevops v0.5.0
```

### Client Version

```
Name: HashiCorp Terraform
Id: hashicorp.terraform
Description: Syntax highlighting and autocompletion for Terraform
Version: 2.26.1
Publisher: HashiCorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform
```

### Terraform Configuration Files

```hcl
terraform {
  
}

locals {
    a = 4
    jeff = true
}

output "name" {
    value = {
        z = 
    }
}
```

![image](https://github.com/hashicorp/terraform-ls/assets/9356891/0ce934e1-9b6b-4bf1-beb8-f300c3337f35)

![image](https://github.com/hashicorp/terraform-ls/assets/9356891/80f8aa44-b49b-49f5-a1d9-a346e75dbfab)

### Log Output

```
2023/05/31 10:46:48 rpc_logger.go:32: Incoming request for "textDocument/completion" (ID 66): {"textDocument":{"uri":"file:///c%3A/Users/PHILDOM/repos/shared-cluster-demos/asd/a.tf"},"position":{"line":15,"character":12},"context":{"triggerKind":1}}
2023/05/31 10:46:48 complete.go:45: Looking for candidates at "a.tf" -> hcl.Pos{Line:16, Column:13, Byte:152}
2023/05/31 10:46:48 complete.go:47: received candidates: lang.Candidates{List:[]lang.Candidate{}, IsComplete:true}
2023/05/31 10:46:48 rpc_logger.go:53: Response to "textDocument/completion" (ID 66): {"isIncomplete":false,"items":[]}
2023/05/31 10:46:48 opts.go:203: Completed 1 requests [1.0522ms elapsed]
```

https://gist.github.com/TeamDman/9925459d1f817b35f0a00a04c9d01ff4

### Expected Behavior

intellisense to provide suggestions for nested expression

### Actual Behavior

intellisense provides no suggestions

### Steps to Reproduce

1. refer to above example

### References

- https://github.com/hashicorp/terraform-ls/blob/v0.31.0/CHANGELOG.md
- https://github.com/hashicorp/terraform-ls/issues/496
- https://github.com/hashicorp/vscode-terraform/issues/1246

**Comment by radeksimko** [comment] 2023-06-01 15:41
@TeamDman Thanks for the report.

We did implement support for certain nested expressions, but there is still a number of cases which we don't handle yet and this is one of them.

I noted down some thoughts in https://github.com/hashicorp/hcl-lang/issues/277 which also contains another example with the same root cause (involving `templatefile()`). TL;DR is that currently when we don't know the type we imply `{ }` to be an object, rather than a map. This mirrors Terraform's own behaviour but is not helpful in many situations.

**Comment by radeksimko** [comment] 2023-06-06 12:08
Just realised that we also captured the problem in this repo already under https://github.com/hashicorp/terraform-ls/issues/1257 - The example there involves `locals` too, although more directly (without `output`).

I'm going to close this one as a duplicate, I hope that's okay. Let me know if you believe that linked issue doesn't cover your problem and we can reopen or discuss further.

**Closed by radeksimko** 2023-06-06 12:08 UTC
Labels: enhancement, textDocument/completion
