### ISSUE TITLE
Terraform-ls keeps crashing because of `panic: invalid URI`

### ISSUE THREAD

**Issue by rwblokzijl** [hashicorp/terraform-ls#1177] opened 2023-02-14 12:52 UTC
Terraform ls keeps crashing on all terraform projects i open with the following panic: `panic: invalid URI`

### Server Version

```
0.30.1
```

### Terraform Version

```
1.3.7
```

### Client Version

```
NVIM v0.8.2
https://github.com/neovim/nvim-lspconfig
```

### Log Output

```
[ERROR][2023-02-14 13:34:43] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"2023/02/14 13:34:43 jobs.go:246: retrying on obj is nil\n"
[ERROR][2023-02-14 13:34:43] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"panic: invalid URI: <nil>\n\ngoroutine 102 [running]:\n"
[ERROR][2023-02-14 13:34:43] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"github.com/hashicorp/terraform-ls/internal/uri.MustParseURI({0xc001c260c0?, 0x12ce37c?})\n\tgithub.com/hashicorp/terraform-ls/internal/uri/uri.go:113 +0x7d\ngithub.com/hashicorp/terraform-ls/internal/document.DirHandleFromURI(...)\n\tgithub.com/hashicorp/terraform-ls/internal/document/dir_handle.go:37\ngithub.com/hashicorp/terraform-ls/internal/document.HandleFromURI({0xc001c260c0, 0x39})\n\tgithub.com/hashicorp/terraform-ls/internal/document/handle.go:30 +0xf6\ngithub.com/hashicorp/terraform-ls/internal/lsp.HandleFromDocumentURI(...)\n\tgithub.com/hashicorp/terraform-ls/internal/lsp/file_handler.go:9\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).TextDocumentHover(0xc000146000, {0x12d5500, 0xc004c24360}, {{{0xc001c260c0?, 0xc000916ea8?}}, {0x4ddabe?, 0x0?}})\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/hover.go:16 +0x131\nreflect.Value.call({0xaa9160?, 0xc0037201e0?, 0xc000917550?}, {0xb50749, 0x4}, {0xc004c245d0, 0x2, 0x40daa7?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xaa9160?, 0xc0037201e0?, 0xaec760?}, {0xc004c245d0?, 0xc0037201e0?, 0xc00068e100?})\n\treflect/value.go:368 +0xbc\n"
[ERROR][2023-02-14 13:34:43] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"github.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({0x12d5500?, 0xc004c24360?}, 0x10?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:236 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(...)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:25\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.handle({0x12d5500, 0xc004c24360}, 0xab33a0?, {0xaa9160?, 0xc0037201e0?})\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:579 +0x69\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).Assigner.func12({0x12d5500?, 0xc004c242d0?}, 0x2?)\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:240 +0x130\nreflect.Value.call({0xaca2e0?, 0xc00011c180?, 0x0?}, {0xb50749, 0x4}, {0xc004c24300, 0x2, 0xa87240?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xaca2e0?, 0xc00011c180?, 0xc004c242d0?}, {0xc004c24300?, 0xaf3ec0?, 0xc00322c200?})\n\treflect/value.go:368 +0xbc\ngithub.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({0x12d5500?, 0xc004c242d0?}, 0xc0003220c0?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:236 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(0xc00013e000?, {0x12d5500?, 0xc004c242d0?}, 0xc00322c200?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:25 +0x2f\ngithub.com/creachadair/jrpc2.(*Server).invoke(0xc000122340, {0x12d5458?, 0xc00322c240?}, {0x12d1f20, 0xc00013a2e0}, 0xc00322c200)\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:384 +0x166\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1()\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:256 +0x1ac\ngithub.com/creachadair/jrpc2.(*Server).serve.func1()\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:178 +0x5a\ncreated by github.com/creachadair/jrpc2.(*Server).serve\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:176 +0x25\n"
```

### Expected Behavior
No crash

### Actual Behavior
Crash

**Comment by radeksimko** [comment] 2023-02-14 13:05
Hi @rwblokzijl 
The attached log output would indicate a client-side bug, but I cannot be sure without seeing more of the log.

`panic: invalid URI: <nil>` part is useful, and indicates that we somehow ended up with empty URI, but it's not clear to me how. i.e. I'd need to see the exact shape of any preceding request sent by the client.

Would you mind sharing the whole log, or at least enough preceding lines which contain the last received RPC request and the rest of the panic stacktrace?

Thanks!

**Comment by rwblokzijl** [comment] 2023-02-14 13:28
@radeksimko thanks for the quick response!

Is this what you're looking for?:
```
[ERROR][2023-02-14 14:24:48] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2023/02/14 14:24:48 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 2): {"position":{"character":0,"line":0},"textDocument":{"uri":"\\/home\\/REDACTED/main.tf"}}\n2023/02/14 14:24:48 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 3): {"position":{"character":0,"line":0},"textDocument":{"uri":"\\/home\\/REDACTED/main.tf"}}\n'
[ERROR][2023-02-14 14:24:48] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"panic: invalid URI: <nil>\n\ngoroutine 62 [running]:\ngithub.com/hashicorp/terraform-ls/internal/uri.MustParseURI({0xc0035b20c0?, 0x12ce37c?})\n\tgithub.com/hashicorp/terraform-ls/internal/uri/uri.go:113 +0x7d\ngithub.com/hashicorp/terraform-ls/internal/document.DirHandleFromURI(...)\n\tgithub.com/hashicorp/terraform-ls/internal/document/dir_handle.go:37\ngithub.com/hashicorp/terraform-ls/internal/document.HandleFromURI({0xc0035b20c0, 0x39})\n\tgithub.com/hashicorp/terraform-ls/internal/document/handle.go:30 +0xf6\ngithub.com/hashicorp/terraform-ls/internal/lsp.HandleFromDocumentURI(...)\n\tgithub.com/hashicorp/terraform-ls/internal/lsp/file_handler.go:9\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).TextDocumentHover(0xc000146000, {0x12d5500, 0xc000783020}, {{{0xc0035b20c0?, 0xc001422ea8?}}, {0x4ddabe?, 0x0?}})\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/hover.go:16 +0x131\nreflect.Value.call({0xaa9160?, 0xc004b221d0?, 0xc001423550?}, {0xb50749, 0x4}, {0xc000783950, 0x2, 0x40daa7?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xaa9160?, 0xc004b221d0?, 0xaec760?}, {0xc000783950?, 0xc004b221d0?, 0xc0027e2100?})\n\treflect/value.go:368 +0xbc\ngithub.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({0x12d5500?, 0xc000783020?}, 0x10?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:236 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(...)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:25\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.handle({0x12d5500, 0xc000783020}, 0xab33a0?, {0xaa9160?, 0xc004b221d0?})\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:579 +0x69\ngithub.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).Assigner.func12({0x12d5500?, 0xc000782d50?}, 0x2?)\n\tgithub.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:240 +0x130\nreflect.Value.call({0xaca2e0?, 0xc00011c180?, 0x0?}, {0xb50749, 0x4}, {0xc000782d80, 0x2, 0xa87240?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xaca2e0?, 0xc00011c180?, 0xc000782d50?}, {0xc000782d80?, 0xaf3ec0?, 0xc0025fe180?})\n\treflect/value.go:368 +0xbc\ngithub.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({"
[ERROR][2023-02-14 14:24:48] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	"0x12d5500?, 0xc000782d50?}, 0xc004c0c0a8?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:236 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(0xc00013e000?, {0x12d5500?, 0xc000782d50?}, 0xc0025fe180?)\n\tgithub.com/creachadair/jrpc2@v0.42.0/handler/handler.go:25 +0x2f\ngithub.com/creachadair/jrpc2.(*Server).invoke(0xc000122270, {0x12d5458?, 0xc0025fe1c0?}, {0x12d1f20, 0xc00013a720}, 0xc0025fe180)\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:384 +0x166\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1()\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:256 +0x1ac\ngithub.com/creachadair/jrpc2.(*Server).serve.func1()\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:178 +0x5a\ncreated by github.com/creachadair/jrpc2.(*Server).serve\n\tgithub.com/creachadair/jrpc2@v0.42.0/server.go:176 +0x25\n"
```

**Comment by radeksimko** [comment] 2023-02-14 13:50
Thank you, this is pretty much what I was looking for!

```
2023/02/14 14:24:48 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 6): {"position":{"character":0,"line":0},"textDocument":{"uri":"\\/home\\/REDACTED/main.tf"}}
2023/02/14 14:24:48 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 2): {"position":{"character":0,"line":0},"textDocument":{"uri":"\\/home\\/REDACTED/main.tf"}}
2023/02/14 14:24:48 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 3): {"position":{"character":0,"line":0},"textDocument":{"uri":"\\/home\\/REDACTED/main.tf"}}
```

Unless you redacted anything from the beginning of those URIs, then I can confirm this is a client-side bug, where the client (NVIM) sends us what appears to be file path, rather than URI. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri  A possible correct URI for that path would be `"file:///home/REDACTED/main.tf"`.

Hence I would suggest filing a bug report to NeoVim and attaching that part of log.

Out of interest, would you mind finding the `initialize` request in the log as well? It should be the very first request with `ID 0` and it should also have URIs. I wonder if the URI(s) there are correct, or if we just silently fail the validation there.

**Comment by rwblokzijl** [comment] 2023-02-14 13:57
I did add REDACTED myself. All the paths of the hover event end in `main.tf`

Here is the 2 lines with "initialize" in it (i again redacted part of the paths)
```
[ERROR][2023-02-14 14:24:46] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2023/02/14 14:24:46 rpc_logger.go:29: Incoming request for "initialize" (ID 1): {"initializationOptions":{},"trace":"off","processId":1380575,"clientInfo":{"version":"0.8.2","name":"Neovim"},"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","Empty","QuickFix","Refactor","RefactorExtract","RefactorInline","RefactorRewrite","Source","SourceOrganizeImports","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"isPreferredSupport":true},"implementation":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true},"documentationFormat":["markdown","plaintext"],"activeParameterSupport":true}},"definition":{"linkSupport":true},"rename":{"dynamicRegistration":false,"prepareSupport":true},"hover":{"dynamicRegistration":false,"contentFormat":["markdown","plaintext"]},"declaration":{"linkSupport":true},"completion":{"completionItem":{"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"commitCharactersSupport":true,"preselectSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"labelDetailsSupport":true},"insertTextMode":1,"dynamicRegistration":false,"contextSupport":true,"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]}},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"references":{"dynamicRegistration":false},"synchronization":{"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false,"didSave":true},"publishDiagnostics":{"tagSupport":{"valueSet":[1,2]},"relatedInformation":true}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":false}},"showDocument":{"support":false},"workDoneProgress":true},"callHierarchy":{"dynamicRegistration":false},"workspace":{"workspaceEdit":{"resourceOperations":["rename","create","delete"]},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalWorkspaceSymbolSupport":true},"configuration":true,"workspaceFolders":true,"applyEdit":true}},"workspaceFolders":[{"uri":"file:\\/\\/\\/home\\/REDACTED","name":"\\/home\\/REDACTED"}],"rootPath":"\\/home\\/REDACTED","rootUri":"file:\\/\\/\\/home\\/REDACTED"}\n'
[ERROR][2023-02-14 14:24:46] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2023/02/14 14:24:46 rpc_logger.go:50: Response to "initialize" (ID 1): {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":[".","["],"resolveProvider":true,"completionItem":{}},"hoverProvider":true,"signatureHelpProvider":{},"declarationProvider":{},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["source.formatAll.terraform"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"executeCommandProvider":{"commands":["terraform-ls.module.callers","terraform-ls.module.calls","terraform-ls.module.providers","terraform-ls.module.terraform","terraform-ls.rootmodules","terraform-ls.terraform.init","terraform-ls.terraform.validate"],"workDoneProgress":true},"semanticTokensProvider":{"legend":{"tokenTypes":[],"tokenModifiers":[]},"full":false},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}},"experimental":{"referenceCountCodeLens":false,"refreshModuleProviders":false,"refreshModuleCalls":false,"refreshTerraformVersion":false}},"serverInfo":{"name":"terraform-ls","version":"0.30.1"}}\n2023/02/14 14:24:46 opts.go:205: Completed 1 requests [922.821µs elapsed]\n2023/02/14 14:24:46 walker.go:214: walking of {file:///home/REDACTED/.terraform/modules} finished\n'
```

**Comment by rwblokzijl** [comment] 2023-02-14 14:00
I would be willing to share you the whole log, with full paths in private if neccesary.

**Comment by radeksimko** [comment] 2023-02-14 14:07
To put it very simply, per the previous log, the following

```
/home/REDACTED/main.tf
```
is meant to be
```
file:///home/REDACTED/main.tf
```
(subject to escaping)

--- 

Thank you for sharing the `initialize` request as well - that appears to have correctly formatted URIs in it 👍🏻 , unlike the `textDocument/hover` requests.

```json
{
  "workspaceFolders": [
    {"uri": "file:\\/\\/\\/home\\/REDACTED", "name":"\\/home\\/REDACTED"}
  ],
  "rootPath": "\\/home\\/REDACTED",
  "rootUri": "file:\\/\\/\\/home\\/REDACTED"
}
```

Therefore I conclude there's nothing we can do on the server side, as this is violation of the protocol by the client (NeoVim) and should be fixed in NeoVim, or its LSP client logic as it likely affects other servers/languages too.

**Closed by radeksimko** 2023-02-14 14:07 UTC
Labels: waiting-response, editor/neovim

**Comment by rwblokzijl** [comment] 2023-02-14 14:11
@radeksimko thank you, i will figure it out within the client. However shouldn't terraform-ls just drop bad requests instead of panic?

**Comment by radeksimko** [comment] 2023-02-14 14:18
I'm not sure if dropping requests in this specific scenario would be better. While we use intentional `panic` very rarely, this is one of the cases where I'd say it's useful, since it prompts the end-user to report very obvious, but rare bugs such as these.

If we were to ignore it, then someone would more likely to complain to us that "hover isn't working" and if they even bothered reporting it at all, it would not be as useful starting point for further debugging.

We have in the past decided to ignore certain odd violations, but something like this should be generally very rare. It's not always easy to find the balance between not upsetting too many users and still contribute to reporting and fixing buggy clients. 😅 

With that in mind: Thank you for reporting this and helping the wider community.

**Comment by rwblokzijl** [comment] 2023-02-14 14:43
Completely understandable. But for the record, i came asking here, because the logs said `panic`. If it said "got invalid url format from client" then i would've created a ticket at the client.

**Comment by radeksimko** [comment] 2023-02-14 16:34
> If it said "got invalid url format from client" then i would've created a ticket at the client.

Understood. I suppose we could be a bit smarter in the wording of the panic message to indicate this is a client-side message, but then again - it should be so rare, that the triage effort related to that is justified.

The key here is that `panic` causes the whole server to exit, making it very obvious to the user something has gone very wrong - and that's what I think is worth keeping, since you (maybe not you specifically, but speaking about an average user) would less likely check the log if it didn't crash and hover only silently stopped working.
