### ISSUE TITLE
Module Variable Intellisense does not work on registry submodules

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform-ls#1102] opened 2022-10-28 18:43 UTC
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/15258962/198709523-d9be7a88-7c01-48fd-a772-60eba2f5ec3e.png)

Works fine with non-submodules (per original feature PR example)
![image](https://user-images.githubusercontent.com/15258962/198709705-031114fb-0ea7-408f-9d1b-5fe1f9e47775.png)

Extension version: 2.24.3
VS Code version: Code - Insiders 1.73.0-insider (c3eebaead9d3bf1cb961b91fca1b8af31990d328, 2022-10-26T09:31:30.519Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.62GB free)|
|Process Argv|--crash-reporter-id f92bfe6d-d926-430e-8c73-f9d1695af3c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
pyind367:30587847
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009
gswce2:30598411
j6j51389:30596843

```

</details>

**Comment by radeksimko** [comment] 2022-10-31 10:34
Reproduced the bug, thank you for the report.

Attaching plaintext config for posterity:

```hcl
module "palofw_vm" {
  source = "PaloAltoNetworks/vmseries-modules/azurerm/modules/vmseries"
  
}
```

Since all the functionality responsible for the module IntelliSense is provided by the language server I moved the issue here under `terraform-ls` repository.

**Comment by smaftoul** [comment] 2023-03-15 19:52
Is this a duplicate of #1035 ?
Any hint as if this would be easy to implement ?

**Comment by radeksimko** [comment] 2023-03-16 07:58
@smaftoul Good catch, this is indeed a duplicate.

We can discuss implementation as part of #1035

**Closed by radeksimko** 2023-03-16 07:58 UTC
Labels: bug
