### ISSUE TITLE
Support for Link to Resource / Data Object Documentation In Editor Pop Up

### ISSUE THREAD

**Issue by seanturner026** [hashicorp/terraform-ls#765] opened 2022-01-13 00:10 UTC
### Current Version
```
v0.25.2
```

### Use-cases

When editing or creating a new resource, I frequently need to go to the terraform docs. This generally involves going to my browser URL bar, starting to type aws terraform $resource name. I would like to have a link hard coded to the documentation for the resource or data object **in the editor pop up**, which appears when mousing over a resource or data object.

### Attempted Solutions

N/A

### Proposal

This pop up appears when  I mouse over the resource. Currently, not very much information is provided aside from the fact that this object is a resource, and the provider version. I think seeing a link to the **latest** terraform documentation would be very helpful. This should be feasible considering that there is no version hardcoded in the link to the documentation

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

<img width="482" alt="Screen Shot 2022-01-13 at 1 01 57 PM" src="https://user-images.githubusercontent.com/30396892/149242473-f692fb69-9172-4a4d-88d6-61af8ff1f156.png">

### Related LSP methods

Unsure. Sorry.

**Comment by radeksimko** [comment] 2022-01-13 08:42
Hi @seanturner026 
Thanks for the request.

I believe this is a duplicate of https://github.com/hashicorp/terraform-ls/issues/190 so I'm going to close this issue to keep the conversation in one place.

We also track https://github.com/hashicorp/vscode-terraform/issues/677 on the VS Code extension side, although all of the work will basically happen on LS side.

Either way there's some work to be done first on the Terraform Registry side, to ensure that we have links which are stable wrt resource and data source names. i.e. that we can guarantee that https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group is a valid link for `aws_cloudwatch_log_group`. There a convention, but certainly no guarantees.

**Closed by radeksimko** 2022-01-13 08:42 UTC
Labels: enhancement
