### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by jellybob** [hashicorp/terraform-ls#97] opened 2020-04-02 20:25 UTC
I'm building an application using a monorepo, with my Terraform config in the sub-directory `terraform/`. This currently results in any Terraform file which references files failing validation in VS Code, despite being valid.

I believe this is caused by Terraform being run for validation from the root of the repository, while the actual runs are done from the `terraform` directory.

**Comment by radeksimko** [comment] 2020-05-12 19:42
Hi @jellybob 
I agree that the workflow you described should be supported.

That said I'm going to close this issue as a duplicate of https://github.com/hashicorp/terraform-ls/issues/32 which also explains how we may tackle the problem and what exactly needs addressing.

**Closed by radeksimko** 2020-05-12 19:42 UTC
